### ISSUE TITLE
VSCode-Insiders: Cannot read the properties of undefined (read 'binding')

### ISSUE THREAD

**Issue by hs1955** [GitLiveApp/GitLive#144]
Issue Type: **Bug**

Hello GitLive members!
I've just installed the GitLive extension for VSCode Insiders, and I encountered the following error:

Cannot read the properties of undefined (read 'binding')
![image](https://user-images.githubusercontent.com/92299208/222122925-bd369804-5dc3-45a0-a45e-4f8f53cc42be.png)

I tried restarting VSCode-Insiders, trying both the pre-release and the stable-release version of GitLive, restarting my laptop, updating the everyting on my OS but I still get the same error. Have not managed to get past this error yet.

How can I go about resolving this?

Information:
- My OS Version: Ubuntu 22.04.2 LTS

Info from VSCode, Help > About:
- Version: 1.76.0-insider
- Commit: 92da9481c0904c6adfe372c12da3b7748d74bdcb
- Date: 2023-02-28T11:50:46.070Z
- Electron: 19.1.11
- Chromium: 102.0.5005.196
- Node.js: 16.14.2
- V8: 10.2.154.26-electron.0
- OS: Linux x64 5.19.0-32-generic snap
- Sandboxed: Yes

Do let me know about anything else you would like from me, I would love to try this extension out for developing in Java with teammates using IntelliJ and VSCode-Insiders.

Many thanks

**Comment by Ygnys** [comment]
Hi @hs1955, thanks for reporting! We are working on a fix for this, I will update you as soon as it's ready

**Comment by hs1955** [comment]
Oh awesome! I'm glad the problem was located, thank you

**Comment by Ygnys** [comment]
Hi @hs1955 we have just released a new update that fixes the issue. Please let us know how it works for you!

**Comment by hs1955** [comment]
Okie dokie, will try now. I'll let you know if it works

**Comment by hs1955** [comment]
Awesome, the release version of GitLive worked just fine,
![image](https://user-images.githubusercontent.com/92299208/222238145-05961611-4d33-4ef9-a066-896867e7d954.png)

I will try the prelease too:
The pre-release version still does not work.
![image](https://user-images.githubusercontent.com/92299208/222240667-1f11ab41-5f75-49f7-b1bc-eb9cedf8dec5.png)

I get the same error, so I will stick with the release version for the time being.
Thank you very much for the fast response time! The fix worked like a charm, and I've managed to sign in and use GitLive

**Comment by Ygnys** [comment]
Hi @hs1955, glad to hear GitLive is working fine for you! Atm the fix is only available in the stable version, I will let you know once the pre-release version is working in Insiders as well :)

**Comment by nbransby** [comment]
Hi @hs1955 this has also been fixed in the pre-release
